# Luke Symes
## Week11 - 04/04/2021
### Python NumPy Universal Functions

In [1]:
import numpy as np
arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z=[]
for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [2]:
#zip

fname= ("Alice","Bob","Christy")
lname= ("Charlie","Clark","robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'robert'))


In [3]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [4]:
import numpy as np
arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
arr1 = np.random.randn(10)
arr1

array([ 1.97063405,  0.32361448, -0.18503292, -1.61263496, -0.20276345,
        1.99268576,  0.48264733, -0.39303448, -0.64530747,  0.01508071])

In [9]:
arr2 =np.random.randn(10)
arr2

array([ 0.49313315, -1.77049552, -1.39911257,  0.77261819, -1.15152893,
       -0.05725829, -1.11664175, -1.13857434, -0.85876192, -0.88307442])

In [10]:
np.add(arr1,arr2)

array([ 2.4637672 , -1.44688104, -1.58414549, -0.84001677, -1.35429238,
        1.93542747, -0.63399442, -1.53160882, -1.50406939, -0.86799371])

In [11]:
np.maximum(arr1,arr2)

array([ 1.97063405,  0.32361448, -0.18503292,  0.77261819, -0.20276345,
        1.99268576,  0.48264733, -0.39303448, -0.64530747,  0.01508071])

In [12]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print(arr<4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
np.where(arr <4,-1,2)

array([[-1, -1, -1],
       [-1,  2,  2],
       [ 2,  2,  2]])

In [15]:
np.where((arr<4) & (arr>2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array((True,False,True,True,False))

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [17]:
#using list comprehensions
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [18]:
# using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [19]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [20]:
np.where([[True,False],[True,True]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [21]:
from numpy.random import randn
arr = randn (5,5)
arr

array([[-0.38098891, -1.68277661, -1.5587247 ,  1.83176334,  1.74757886],
       [ 1.04802888, -0.73304882, -1.10888979,  1.80515339, -0.16182752],
       [ 0.20942278, -1.02469543,  0.57291649, -0.21506966,  1.06714792],
       [ 0.67378803,  0.3376849 , -1.08012669, -0.44308951, -1.52514043],
       [-0.01454735, -0.03526101,  0.00743838,  1.04757535,  0.59974083]])

In [22]:
np.where(arr<0, 0,arr)

array([[0.        , 0.        , 0.        , 1.83176334, 1.74757886],
       [1.04802888, 0.        , 0.        , 1.80515339, 0.        ],
       [0.20942278, 0.        , 0.57291649, 0.        , 1.06714792],
       [0.67378803, 0.3376849 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00743838, 1.04757535, 0.59974083]])

In [23]:
arr_b = np.array([True,False, True, False, False])

arr_b.any()

True

In [24]:
arr_b.all()

False

In [25]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [26]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [27]:
# Statisical measures
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
arr.sum()

45

In [29]:
arr.sum(0)

array([12, 15, 18])

In [30]:
arr.sum(1)

array([ 6, 15, 24])

In [31]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [32]:
print(arr)
np.sum(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [33]:
print(arr)
np.sum(arr, axis=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [34]:
arr.mean()

5.0

In [35]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [36]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [37]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [38]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [39]:
arr.var()

6.666666666666667

In [40]:
arr.std()

2.581988897471611

In [43]:
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])

arr.sort()

arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [44]:
#Identity array
i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a = np.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [47]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)

a *i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [48]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [49]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [51]:
#Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr)
print('-------------------')

t = arr.T

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
-------------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [52]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [53]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [55]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [56]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [57]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [59]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [60]:
np.random.random((4,4))

array([[0.64556422, 0.44289509, 0.94005295, 0.07363783],
       [0.80606292, 0.00201706, 0.07244308, 0.98166163],
       [0.37792995, 0.66449182, 0.60826979, 0.84405414],
       [0.59549415, 0.46142219, 0.05871351, 0.73086368]])

In [62]:
from numpy.random import random
random((4,4))

array([[0.63042063, 0.58937346, 0.03655527, 0.39459812],
       [0.86702914, 0.46295591, 0.20132913, 0.61859052],
       [0.70453837, 0.84980792, 0.28017055, 0.38072116],
       [0.92709617, 0.10342999, 0.926381  , 0.72766945]])

In [63]:
from numpy.random import randn
randn(5,5)

array([[ 0.83942741, -0.43550898, -0.68284114,  1.0258108 , -0.91605926],
       [-0.1536265 , -0.16383583,  0.27888991, -0.09291761,  0.93990237],
       [-0.2001429 ,  0.04453439,  1.01050865, -1.54163548, -0.58937856],
       [-1.86548854, -0.30956467,  1.10409364, -0.89794212,  0.13519278],
       [ 0.30960994, -0.43852057, -0.31273972,  0.68255857, -0.30929828]])

In [64]:
randn(5)

array([0.54128735, 1.80283776, 0.08245296, 0.364637  , 0.30741878])

In [65]:
np.random.randint(10,50)

12

In [67]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

import webbrowser
webbrowser.open(website)

True

In [68]:
import pandas as pd