# Luke Symes
## Week11 - 04/04/2021
### Python NumPy Universal Functions

In [3]:
import numpy as np
arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z=[]
for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [4]:
#zip

fname= ("Alice","Bob","Christy")
lname= ("Charlie","Clark","robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'robert'))


In [5]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [6]:
import numpy as np
arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [8]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
arr1 = np.random.randn(10)
arr1

array([-1.05102258, -1.21541936,  0.01619967,  0.21718346, -0.7092513 ,
        1.07660637, -0.54323781, -0.12353279,  0.57720722,  0.85145775])

In [11]:
arr2 =np.random.randn(10)
arr2

array([ 0.03959696, -0.33832328, -0.55104758, -0.32584216, -0.02157479,
        0.60276196, -0.19209297,  0.03238426, -0.89153047,  1.47072815])

In [12]:
np.add(arr1,arr2)

array([-1.01142561, -1.55374265, -0.5348479 , -0.1086587 , -0.73082609,
        1.67936833, -0.73533078, -0.09114854, -0.31432325,  2.3221859 ])

In [13]:
np.maximum(arr1,arr2)

array([ 0.03959696, -0.33832328,  0.01619967,  0.21718346, -0.02157479,
        1.07660637, -0.19209297,  0.03238426,  0.57720722,  1.47072815])

In [14]:
#np.where
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
print(arr<4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [16]:
np.where(arr <4,-1,2)

array([[-1, -1, -1],
       [-1,  2,  2],
       [ 2,  2,  2]])

In [17]:
np.where((arr<4) & (arr>2), -1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array((True,False,True,True,False))

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [21]:
#using list comprehensions
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]
arr3

[1, 20, 3, 4, 50]

In [22]:
# using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])